export const agentCreditAbi = [
  {
    type: "function",
    name: "borrow",
    inputs: [
      { name: "borrowAmount", type: "uint256" },
      { name: "collateralShares", type: "uint256" },
    ],
    outputs: [{ name: "loanId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "repay",
    inputs: [{ name: "loanId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "liquidate",
    inputs: [{ name: "loanId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getCollateralRatio",
    inputs: [{ name: "agent", type: "address" }],
    outputs: [{ name: "ratio", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isHealthy",
    inputs: [{ name: "loanId", type: "uint256" }],
    outputs: [
      { name: "healthy", type: "bool" },
      { name: "healthFactor", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalOwed",
    inputs: [{ name: "loanId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lendingPool",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalBorrowed",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "collateralRatios",
    inputs: [{ name: "tier", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "loans",
    inputs: [{ name: "loanId", type: "uint256" }],
    outputs: [
      { name: "id", type: "uint256" },
      { name: "agent", type: "address" },
      { name: "borrowedAmount", type: "uint256" },
      { name: "collateralShares", type: "uint256" },
      { name: "interestRateBps", type: "uint256" },
      { name: "accruedInterest", type: "uint256" },
      { name: "startBlock", type: "uint256" },
      { name: "lastAccrualBlock", type: "uint256" },
      { name: "repaid", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "LoanCreated",
    inputs: [
      { name: "loanId", type: "uint256", indexed: true },
      { name: "agent", type: "address", indexed: true },
      { name: "borrowed", type: "uint256", indexed: false },
      { name: "collateral", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "LoanRepaid",
    inputs: [
      { name: "loanId", type: "uint256", indexed: true },
      { name: "agent", type: "address", indexed: true },
      { name: "totalRepaid", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "LoanLiquidated",
    inputs: [
      { name: "loanId", type: "uint256", indexed: true },
      { name: "agent", type: "address", indexed: true },
      { name: "liquidator", type: "address", indexed: true },
    ],
  },
] as const;
